# Tests of the faux/limited host-only Ethernet5500 library.

cc_test(
    name = "ethernet_client_test",
    srcs = ["ethernet_client_test.cc"],
    deps = [
        "//googletest:gunit_main",
        "//mcucore/extras/test_tools:print_to_std_string",
        "//mcunet/extras/host/ethernet5500:ethernet_client",
    ],
)
