# TODO(jamessynge): describe this package.

cc_test(
    name = "server_socket_test",
    srcs = ["server_socket_test.cc"],
    deps = [
        "//googletest:gunit_main",
        "//mcunet/extras/test_tools:mock_socket_listener",
        "//mcunet/src:server_socket",
    ],
)
