# Placeholder required so that we can load build_config.bzl from here.

load("//tools/build_defs/testing:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "build_config_bzl",
    srcs = ["build_config.bzl"],
    parse_tests = False,
    visibility = ["//visibility:private"],
)
