#ifndef MCUNET_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
#define MCUNET_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
#include <inttypes.h>

#define MAX_SOCK_NUM 8

#endif  // MCUNET_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
