#ifndef MCUNET_SRC_MCUNET_CONFIG_H_
#define MCUNET_SRC_MCUNET_CONFIG_H_

// Configure McuNet features.
//
// Author: james.synge@gmail.com

#include <McuCore.h>

#ifndef MCU_HAS_PLATFORM_NETWORK_IMPLEMENTATION
#if MCU_HOST_TARGET
#define MCU_HAS_PLATFORM_NETWORK_IMPLEMENTATION 1
#endif  // MCU_HOST_TARGET
#endif  // MCU_HAS_PLATFORM_NETWORK_IMPLEMENTATION

// On the host platform, maybe enable extra logging and debug checks in the HTTP
// request decoder.
#if MCU_HOST_TARGET && MCU_ENABLE_DEBUGGING

#ifndef MCU_REQUEST_DECODER_DISABLE_EXTRA_CHECKS
#define MCU_REQUEST_DECODER_ENABLE_EXTRA_CHECKS
#endif

#ifndef MCU_REQUEST_DECODER_DISABLE_VLOG
#define MCU_REQUEST_DECODER_ENABLE_VLOG
#define MCU_REQUEST_DECODER_VLOG_LEVEL 2
#endif

#endif  // MCU_HOST_TARGET && MCU_ENABLE_DEBUGGING

// If explicitly disabled, disable extra logging and debug checks.
#ifdef MCU_REQUEST_DECODER_DISABLE_EXTRA_CHECKS
#undef MCU_REQUEST_DECODER_ENABLE_EXTRA_CHECKS
#endif

#ifdef MCU_REQUEST_DECODER_DISABLE_VLOG
#undef MCU_REQUEST_DECODER_ENABLE_VLOG
#endif

#endif  // MCUNET_SRC_MCUNET_CONFIG_H_
